language: php

php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3

env:
    - SYMFONY_VERSION=origin/2.8
    - SYMFONY_VERSION=origin/3.4
    - SYMFONY_VERSION=origin/4.2

matrix:
    exclude:
        - php: 5.6
          env: SYMFONY_VERSION=origin/4.2
      

before_script:
    - composer self-update 
script:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction
